name: Build LaTeX "Analisi 2" document
on: [push]
jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4.1.2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Analisi_2/dispense_analisi_2.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: Analisi_2/dispense_analisi_2.pdf
